### ISSUE TITLE
About development environment

### ISSUE THREAD

**Issue by manohito** [natmark/ProcessingKit#24]
This is a wonderful library x). Is there a recommended development environment when I want to contribute to the development of this project? Also, it is best if it is described somewhere about it.

**Comment by natmark** [comment]
Thank you for your comment. I recommend you to use Xcode.

First, please open `ProcessingKitExample/ProcessingKitExample.xcodeproj` .
It is for ProcessingKit demo. Please edit code from demo project.

**Comment by manohito** [comment]
ここのはとりあえず解決できたのでissue閉じます
